### ISSUE TITLE
Milestone3_group-feedback

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/DSCI-532_Alex-Jesica_Bechdel-Test#13]
- What does Bechdel mean?  Explain this somewhere in the app maybe. 
- Really like the hover telling you the movie on the chart
- Plot tabs can have more descriptive names 
- Download results returns whole data set, not the filter selection
- I like the alpha transparency for the pass/fail  
- For plot 2 combine the two histograms so you can more easily compare each how many movies in a year passed/failed the bechdel test  
- I think more formatting on the plots would be nice

**Comment by pak-alex** [comment]
* Additional context was added to app
* Plot tabs now have labels
* Download button was checked
* Histograms were combined

Changes are reflected in [v3.0](https://github.com/UBC-MDS/DSCI-532_Alex-Jesica_Bechdel-Test/tree/v3.0).
