### ISSUE TITLE
Feedback from Linyang Yu

### ISSUE THREAD

**Issue by lyyu0413** [UBC-MDS/DSCI-532_Alex-Jesica_Bechdel-Test#15]
Good 
1. I like the way the app was organized: different panels of plots, different question answered by each plot and they give information about the filter results;
2. I like the multiple selection check box.
3. I like the way they highlight the data by changing alpha values. 
4. I like the plot 3 how they choose the product type.

Suggestions:
1. More informative name for plot 1, 2 and 3;
2. For ‘Download Results’, it’s better to download the filter results compared to the whole dataset. 
3. Change the position of the title for each plot, make it more informative;
4. Maybe it is better to fix the figure size of plot 3 when they have more sub plot. 

Summary

The question is interesting and the way they represent it is excellent.

**Comment by pak-alex** [comment]
1. Labels were added to three plots 
2. Download results button was checked
3. Layout of app was updated 
4. Plot 3 was changed to include more space

Changes are reflected in [v3.0](https://github.com/UBC-MDS/DSCI-532_Alex-Jesica_Bechdel-Test/tree/v3.0).
